language: java

script:
- sudo apt-get -y install docker
- docker pull oracle/glassfish
- pwd
- ls 
- ls build/libs/
- docker --version
- docker run hello-world
- docker run oracle/glassfish 
- docker container ls
