language: java

script:
- sudo apt-get -y install docker
- docker pull glassfish:4.0
- pwd
- ls 
- ls build/libs/
- docker --version
- docker run hello-world
- docker image ls
- travis_wait 20 docker run glassfish:4.0
- export GF_INST_DIR=/glassfish4
- $GF_INST_DIR/bin/asadmin deploy build/libs/sanwada.war
- docker container ls
