language: java

script:
- sudo apt-get -y install docker
- docker pull oracle/glassfish:4.1.1
- pwd
- ls 
- ls build/libs/
- docker --version
- docker run hello-world
- docker run oracle/glassfish:4.1.1 
- export GF_INST_DIR=/glassfish5
- $GF_INST_DIR/bin/asadmin deploy build/libs/sanwada.war
- docker container ls
